services:
  kappsdb:
    image: mariadb:10.6.20-ubi9
    # restart: always
    env_file:
      - .env
    # hostname: ${MYSQL_HOST} 
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    volumes:
      - .:/db
    working_dir: /db
    networks:
      - mynet
    #entrypoint: [ 'bash', '-c', 'sleep 5 && ${MYSQL_ROOT_CONNECTION} < ${MYSQL_DUMP_FILE} && ${MYSQL_ROOT_CONNECTION} -e "${GRANTS_KAPPDB_SCHEMA}" && ${MYSQL_ROOT_CONNECTION} -e "${GRANTS_APP_SCHEMA}"']
  etga_test:
    #platform: linux/arm64/v8 # SnapDragon Processors and Mac M-Series
    #platform: linux/amd64 # WINDOWS x86 / MAC x86
    image: kennycarcamo/kapps:etga
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8001:3000"
    volumes:
      - .:/app/codigo
    working_dir: /app/codigo
    entrypoint: [ "bash", "-c", "python3 main.py"]
    networks:
      - mynet
networks:
  mynet:
    driver: bridge